"""
generate_module.py

This script generates a simple educational module PDF using the
ReportLab library. It demonstrates how to produce a multi‑page PDF
similar in structure to the example teaching module provided by the
user. The resulting PDF includes:

1. A cover page with a coloured header, title, topic, author and logo.
2. A module information page with key details in a table format.
3. A content page with bullet points and a sample table for activities.

To run this script, install reportlab via pip:

    pip install reportlab

Then execute:

    python generate_module.py

The script will produce a file named sample_module.pdf in the same
directory.
"""

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import Table, TableStyle, Paragraph, SimpleDocTemplate, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import os


def build_cover(canv, subject, topic, author, logo_path):
    """Draw the cover page on the given canvas."""
    width, height = A4
    # Draw coloured header
    canv.setFillColor(colors.HexColor('#0f766e'))
    canv.rect(0, height - 6*cm, width, 6*cm, fill=1, stroke=0)
    # Title text
    canv.setFillColor(colors.white)
    canv.setFont('Helvetica-Bold', 32)
    canv.drawString(2*cm, height - 3*cm, f"Modul Ajar {subject}")
    canv.setFont('Helvetica', 18)
    canv.drawString(2*cm, height - 4.5*cm, f"Topik: {topic}")
    # Author text
    canv.setFillColor(colors.HexColor('#475569'))
    canv.setFont('Helvetica', 12)
    canv.drawString(2*cm, 4*cm, f"Penyusun: {author}")
    # Draw logo if available
    if logo_path and os.path.exists(logo_path):
        logo_width = 4.5*cm
        logo_height = 2.5*cm
        canv.drawImage(logo_path, width - logo_width - 2*cm, height - 3.5*cm, width=logo_width, height=logo_height, preserveAspectRatio=True, mask='auto')
    # Footer
    canv.setFont('Helvetica-Oblique', 10)
    canv.setFillColor(colors.HexColor('#94a3b8'))
    canv.drawCentredString(width/2, 2*cm, 'Generated by EduText Engine')
    canv.showPage()


def build_info_page(canv, info_data):
    """Create a second page with module information details."""
    width, height = A4
    styles = getSampleStyleSheet()
    # Start a new page
    canv.showPage()
    canv.setFillColor(colors.HexColor('#ffffff'))
    canv.setFont('Helvetica-Bold', 20)
    canv.setFillColor(colors.HexColor('#0f766e'))
    canv.drawString(2*cm, height - 2.5*cm, 'Informasi Modul')
    # Build a simple table with the info data
    data = [[key, value] for key, value in info_data.items()]
    table = Table(data, colWidths=[5*cm, 11*cm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e7f5f1')),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#cbd5e1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('FONT', (0, 0), (-1, -1), 'Helvetica', 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    # Calculate table width and height
    w, h = table.wrap(0, 0)
    # Draw table on canvas
    table.drawOn(canv, 2*cm, height - 4*cm - h)


def build_content_page(canv):
    """Add a content page with bullet list and sample activities table."""
    width, height = A4
    canv.setFillColor(colors.white)
    canv.showPage()
    # Title
    canv.setFont('Helvetica-Bold', 20)
    canv.setFillColor(colors.HexColor('#0f766e'))
    canv.drawString(2*cm, height - 2.5*cm, 'Rencana Pelaksanaan')
    # Bulleted content
    text = [
        'Menjelaskan konsep dasar materi secara singkat dan jelas.',
        'Menampilkan contoh soal dan pembahasan.',
        'Melakukan tanya jawab singkat dengan peserta didik.',
        'Memberikan latihan mandiri untuk memperkuat pemahaman.',
    ]
    y = height - 4*cm
    canv.setFont('Helvetica', 12)
    canv.setFillColor(colors.HexColor('#475569'))
    bullet = u'\u2022'
    for line in text:
        canv.drawString(3*cm, y, f'{bullet} {line}')
        y -= 0.7*cm
    # Sample table: 3 activities with descriptions
    table_data = [
        ['Tahap', 'Deskripsi'],
        ['Pendahuluan', 'Orientasi dan apersepsi'],
        ['Inti', 'Penyampaian materi dan diskusi'],
        ['Penutup', 'Refleksi dan evaluasi'],
    ]
    table = Table(table_data, colWidths=[4*cm, 12*cm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e7f5f1')),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#cbd5e1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('FONT', (0, 0), (-1, -1), 'Helvetica', 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    # Wrap and draw table on the canvas under the bulleted text
    w, h_table = table.wrap(0, 0)
    table.drawOn(canv, 2*cm, y - h_table - 1*cm)


def generate_module(subject='Fisika', topic='Hukum Newton', author='Nama Anda', output_path='sample_module.pdf', logo_path=None):
    """Generate a sample module PDF."""
    canv = canvas.Canvas(output_path, pagesize=A4)
    # Build each page
    build_cover(canv, subject, topic, author, logo_path)
    # Info data: adjust as needed
    info = {
        'Mata Pelajaran': subject,
        'Topik': topic,
        'Penyusun': author,
        'Kelas/Semester': 'XI / Ganjil',
        'Jenis Modul': 'Modul Ajar',
    }
    # Note: build_info_page will start a new page automatically
    build_info_page(canv, info)
    build_content_page(canv)
    canv.save()
    print(f'Module generated at {output_path}')


if __name__ == '__main__':
    # Use the logo from the project if available
    logo = os.path.join(os.path.dirname(__file__), 'img', 'logo.png')
    generate_module(output_path='sample_module.pdf', logo_path=logo)