import { Worker } from 'bullmq';
import Redis from 'ioredis';
import { chromium } from 'playwright';
import { prisma } from '../src/lib/db';
import { renderTemplate } from '../src/lib/template-renderer';
import { putPdf } from '../src/lib/storage';

const connection = new Redis(process.env.REDIS_URL ?? '');

new Worker(
  'pdf-generation',
  async (job) => {
    const { documentId } = job.data as { documentId: string };

    const document = await prisma.document.findUnique({ where: { id: documentId } });
    if (!document) {
      throw new Error('Document not found');
    }

    await prisma.document.update({
      where: { id: documentId },
      data: { status: 'GENERATING', errorMessage: null }
    });

    try {
      const html = renderTemplate({ docType: document.docType, content: document.contentJson as any });
      const browser = await chromium.launch({
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle' });
      await page.emulateMediaType('print');

      const pdf = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '20mm', right: '15mm', bottom: '20mm', left: '15mm' },
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate:
          '<div style="font-size:9px;width:100%;padding:0 12mm;display:flex;justify-content:space-between;">
            <span>Generated by EduText</span>
            <span>Halaman <span class="pageNumber"></span> / <span class="totalPages"></span></span>
          </div>'
      });

      await browser.close();

      const key = `documents/${document.id}.pdf`;
      await putPdf({ key, body: pdf });

      await prisma.document.update({
        where: { id: documentId },
        data: { status: 'READY', pdfStorageKey: key }
      });
    } catch (error) {
      await prisma.document.update({
        where: { id: documentId },
        data: { status: 'FAILED', errorMessage: (error as Error).message }
      });
      throw error;
    }
  },
  { connection }
);
